import { test, expect } from './fixtures/config-test-fixtures.ts'
import { loadWithMediaViewer, mediaViewerFrame } from './fixtures/media-viewer.ts'
import type { Page } from 'playwright'

declare global {
  // matches `src/ui/pages/render-media.tsx` so `page.evaluate` can read the props
  var renderMedia: {
    kind: 'image' | 'video' | 'audio' | 'pdf' | 'text' | 'json'
    contentType: string
    contentLength: number | null
    cid: string
    ipfsPath: string
    displayName: string
    filename: string
    url: string
  } | undefined
}

/**
 * End-to-end coverage for the media-viewer wrapper, the workaround for
 * the Chromium "Save As" bug introduced in #574.
 *
 * Each media type runs through two URL shapes:
 *
 * 1. `/ipfs/<dir>/<filename>`: verified-fetch reads the content-type from
 * the path extension, and `displayName` matches the filename.
 * 2. `/ipfs/<file>` (bare CID): verified-fetch sniffs the bytes,
 * `displayName` falls back to `<cid>`, and `filename` becomes
 * `<cid>.<ext>`.
 *
 * Fixtures live as checked-in CAR files generated by
 * `test-e2e/fixtures/data/generate.ts`; the suite needs no kubo IO at
 * runtime.
 *
 * Each fixture exists in two encodings, dag-pb and raw-codec. The active
 * tests use the dag-pb form because dag-pb files route through
 * `plugin-handle-unixfs`, which sniffs correctly. Raw-codec files
 * short-circuit content-type sniffing in verified-fetch's
 * `plugin-handle-raw` today; the commented-out block at the end of the
 * file pins those CIDs and re-activates as soon as upstream lands a fix.
 */
test.describe('media-viewer wrapper', () => {
  // dag-pb directories wrapping the dag-pb file blocks
  const pngDir = 'bafybeidozaq7mrxpyrhdvk36utvkhk5x6wanrcsqlj5ntf4fra6ywvwwjq'
  const mp4Dir = 'bafybeihdiqfalahcjx52ciqzkm5p63ofnke4xznpdyhqgafzmbbad7c7fy'
  const pdfDir = 'bafybeid7zzbpchumzjvvuuxmz6bga7fjpefump6ywsxybdyndpazg5pwzi'
  const txtDir = 'bafybeihomvpithtpbfuzv77imsc62n6dg6ornxfy2n4snpjtzreveymijm'
  const jsonDir = 'bafybeig6zo2htnxoq6pt5turvflnawl35b77fpeevc6h7kmerpcua2m74a'

  // dag-pb file CIDs that `plugin-handle-unixfs` can sniff
  const pngFile = 'bafybeiaeud4iphz727hxaemlp46yjuv2ekzorkqirwc2i7bcwxaznoeenu'
  const mp4File = 'bafybeia2onajb25yrs36v4f7mgfeipohxy5b4c4pco3cyyik25qm27gzvy'
  const pdfFile = 'bafybeicnwz34bc263yab46pfi5pfuapo4m42pr3eucgvy525rpkexrkdtq'

  // dag-pb single-file fixtures already shipped by the rest of the suite
  const jpegCid = 'bafybeigdyrzt5sfp7udm7hu76uh7y26nf3efuylqabf3oclgtqy55fbzdi'
  const webmCid = 'bafybeie4vcqkutumw7s26ob2bwqwqi44m6lrssjmiirlhrzhs2akdqmkw4'

  test.describe('path with filename', () => {
    test('PNG', async ({ page, baseURL }) => {
      const response = await loadWithMediaViewer(page, `${baseURL}/ipfs/${pngDir}/pixel.png`)
      await assertWrapperResponse(response)

      const props = await readWrapperProps(page)
      expect(props?.kind).toBe('image')
      expect(props?.contentType).toBe('image/png')
      expect(props?.displayName).toBe('pixel.png')
      expect(props?.filename).toBe('pixel.png')

      await expect(page.locator('img')).toBeVisible()
      await assertDownloadButton(page, 'pixel.png')
    })

    test('MP4', async ({ page, baseURL }) => {
      const response = await loadWithMediaViewer(page, `${baseURL}/ipfs/${mp4Dir}/tiny.mp4`)
      await assertWrapperResponse(response)

      const props = await readWrapperProps(page)
      expect(props?.kind).toBe('video')
      expect(props?.contentType).toBe('video/mp4')
      expect(props?.displayName).toBe('tiny.mp4')
      expect(props?.filename).toBe('tiny.mp4')

      await expect(page.locator('video')).toBeVisible()
      await assertDownloadButton(page, 'tiny.mp4')
    })

    test('PDF', async ({ page, baseURL }) => {
      const response = await loadWithMediaViewer(page, `${baseURL}/ipfs/${pdfDir}/tiny.pdf`)
      await assertWrapperResponse(response)

      const props = await readWrapperProps(page)
      expect(props?.kind).toBe('pdf')
      expect(props?.contentType).toBe('application/pdf')
      expect(props?.displayName).toBe('tiny.pdf')
      expect(props?.filename).toBe('tiny.pdf')

      // `#toolbar=0` hides Chromium's built-in PDF toolbar so users reach
      // for our top-bar Download button instead.
      const iframeSrc = await page.locator('iframe').getAttribute('src')
      expect(iframeSrc).toContain('#toolbar=0')

      await assertDownloadButton(page, 'tiny.pdf')
    })

    test('text', async ({ page, baseURL }) => {
      const response = await loadWithMediaViewer(page, `${baseURL}/ipfs/${txtDir}/readme.txt`)
      await assertWrapperResponse(response)

      const props = await readWrapperProps(page)
      expect(props?.kind).toBe('text')
      expect(props?.contentType).toContain('text/plain')
      expect(props?.displayName).toBe('readme.txt')
      expect(props?.filename).toBe('readme.txt')

      // wrapper renders the text body inside an iframe
      await expect(mediaViewerFrame(page).getByText('hello from a text file')).toBeVisible()
      await assertDownloadButton(page, 'readme.txt')
    })

    test('JSON', async ({ page, baseURL }) => {
      const response = await loadWithMediaViewer(page, `${baseURL}/ipfs/${jsonDir}/data.json`)
      await assertWrapperResponse(response)

      const props = await readWrapperProps(page)
      expect(props?.kind).toBe('json')
      expect(props?.contentType).toContain('application/json')
      expect(props?.displayName).toBe('data.json')
      expect(props?.filename).toBe('data.json')

      await expect(mediaViewerFrame(page).getByText('"hello"')).toBeVisible()
      await assertDownloadButton(page, 'data.json')
    })
  })

  test.describe('bare CID', () => {
    test('PNG', async ({ page, baseURL }) => {
      const response = await loadWithMediaViewer(page, `${baseURL}/ipfs/${pngFile}`)
      await assertWrapperResponse(response)

      const props = await readWrapperProps(page)
      expect(props?.kind).toBe('image')
      expect(props?.contentType).toBe('image/png')
      expect(props?.displayName).toBe(pngFile)
      expect(props?.filename).toBe(`${pngFile}.png`)

      await expect(page.locator('img')).toBeVisible()
      await assertDownloadButton(page, `${pngFile}.png`)
    })

    test('JPEG', async ({ page, baseURL }) => {
      const response = await loadWithMediaViewer(page, `${baseURL}/ipfs/${jpegCid}`)
      await assertWrapperResponse(response)

      const props = await readWrapperProps(page)
      expect(props?.kind).toBe('image')
      expect(props?.contentType).toBe('image/jpeg')
      expect(props?.displayName).toBe(jpegCid)
      expect(props?.filename).toBe(`${jpegCid}.jpg`)

      await expect(page.locator('img')).toBeVisible()
      await assertDownloadButton(page, `${jpegCid}.jpg`)
    })

    test('MP4', async ({ page, baseURL }) => {
      const response = await loadWithMediaViewer(page, `${baseURL}/ipfs/${mp4File}`)
      await assertWrapperResponse(response)

      const props = await readWrapperProps(page)
      expect(props?.kind).toBe('video')
      expect(props?.contentType).toBe('video/mp4')
      expect(props?.filename).toBe(`${mp4File}.mp4`)

      await expect(page.locator('video')).toBeVisible()
      await assertDownloadButton(page, `${mp4File}.mp4`)
    })

    test('WebM', async ({ page, baseURL }) => {
      const response = await loadWithMediaViewer(page, `${baseURL}/ipfs/${webmCid}`)
      await assertWrapperResponse(response)

      const props = await readWrapperProps(page)
      expect(props?.kind).toBe('video')
      expect(props?.contentType).toBe('video/webm')
      expect(props?.filename).toBe(`${webmCid}.webm`)

      await expect(page.locator('video')).toBeVisible()
      await assertDownloadButton(page, `${webmCid}.webm`)
    })

    test('PDF', async ({ page, baseURL }) => {
      const response = await loadWithMediaViewer(page, `${baseURL}/ipfs/${pdfFile}`)
      await assertWrapperResponse(response)

      const props = await readWrapperProps(page)
      expect(props?.kind).toBe('pdf')
      expect(props?.contentType).toBe('application/pdf')
      expect(props?.filename).toBe(`${pdfFile}.pdf`)

      const iframeSrc = await page.locator('iframe').getAttribute('src')
      expect(iframeSrc).toContain('#toolbar=0')

      await assertDownloadButton(page, `${pdfFile}.pdf`)
    })

    // text and JSON have no bare-CID test on purpose: file-type leaves
    // text formats alone, so verified-fetch falls back to
    // `application/octet-stream`, which the wrapper ignores. Bare-CID
    // navigation serves the raw bytes (the correct behaviour), leaving
    // no wrapper UI to assert on.
  })

  test('Download button points at the bypass URL', async ({ page, baseURL }) => {
    await loadWithMediaViewer(page, `${baseURL}/ipfs/${txtDir}/readme.txt`)

    const href = await page.locator('a:has-text("Download")').getAttribute('href')
    expect(href).toBe(`?download=true&filename=${encodeURIComponent('readme.txt')}`)
  })

  /*
   * TODO: re-enable once `plugin-handle-raw` in verified-fetch sniffs the
   * content-type for raw-codec single-block files instead of returning
   * `application/vnd.ipld.raw`.
   *
   * Modern IPFS tooling (Kubo with `--cid-version=1`, helia/unixfs's
   * default `rawLeaves: true`) emits raw-codec single-block files for any
   * content that fits in one block. The HTTP path-gateway spec requires
   * sniffing the content-type when no Accept or format hint arrives, but
   * `plugin-handle-raw` short-circuits to `application/vnd.ipld.raw`, so
   * the bytes carry recognisable PDF / PNG / MP4 magic and the wrapper
   * never fires.
   *
   * Each test below pins a raw-codec CID emitted by `generate.ts`. The
   * CAR is already in the fixture store, so the tests run as soon as the
   * block is uncommented.
   *
   *   const pngFileRaw = 'bafkreifc2is7poqxkllbmnfmk4vqq5mabebokzmztuh5yvmgyiyc37d2ve'
   *   const mp4FileRaw = 'bafkreib352b43e2xtocqj5qqfi7kk6xuhurqxx7p2yfmyi44dgfoxmqtnu'
   *   const pdfFileRaw = 'bafkreic2qodhqbmpnxrxl2ddlnps72shuts7a7frvcbkisyq6only3zu74'
   *
   *   test.describe('bare CID (raw codec)', () => {
   *     test('PNG sniffs as image/png and triggers wrapper', async ({ page, baseURL }) => {
   *       const response = await loadWithMediaViewer(page, `${baseURL}/ipfs/${pngFileRaw}`)
   *       await assertWrapperResponse(response)
   *       const props = await readWrapperProps(page)
   *       expect(props?.kind).toBe('image')
   *       expect(props?.contentType).toBe('image/png')
   *     })
   *
   *     test('MP4 sniffs as video/mp4 and triggers wrapper', async ({ page, baseURL }) => {
   *       const response = await loadWithMediaViewer(page, `${baseURL}/ipfs/${mp4FileRaw}`)
   *       await assertWrapperResponse(response)
   *       const props = await readWrapperProps(page)
   *       expect(props?.kind).toBe('video')
   *       expect(props?.contentType).toBe('video/mp4')
   *     })
   *
   *     test('PDF sniffs as application/pdf and triggers wrapper', async ({ page, baseURL }) => {
   *       const response = await loadWithMediaViewer(page, `${baseURL}/ipfs/${pdfFileRaw}`)
   *       await assertWrapperResponse(response)
   *       const props = await readWrapperProps(page)
   *       expect(props?.kind).toBe('pdf')
   *       expect(props?.contentType).toBe('application/pdf')
   *     })
   *   })
   */
})

async function assertWrapperResponse (response: Awaited<ReturnType<typeof loadWithMediaViewer>>): Promise<void> {
  expect(response.status()).toBe(200)
  expect(response.headers()['content-type']).toBe('text/html; charset=utf-8')
}

async function readWrapperProps (page: Page): Promise<typeof globalThis.renderMedia> {
  return page.evaluate(() => globalThis.renderMedia)
}

async function assertDownloadButton (page: Page, expectedFilename: string): Promise<void> {
  const button = page.locator('a:has-text("Download")')
  await expect(button).toBeVisible()
  const href = await button.getAttribute('href')
  expect(href).toContain('download=true')
  expect(href).toContain(`filename=${encodeURIComponent(expectedFilename)}`)
}
